[project]
authors = ["Matt McCormick <matt@mmmccormick.com>"]
channels = ["conda-forge"]
description = "Zstandard compression and decompression and base64 encoding and decoding in WebAssembly."
name = "compress-stringify"
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pnpm = ">=9.12.1,<10"

[feature.python.dependencies]
pytest = ">=8.3.3,<9"
pip = ">=24.2,<25"

[feature.python.pypi-dependencies]
hatch = ">=1.13.0, <2"
pyodide-py = ">=0.26.3, <0.27"
itkwasm-compress-stringify-wasi = { path = "python/itkwasm-compress-stringify-wasi", editable = true }
itkwasm-compress-stringify = { path = "python/itkwasm-compress-stringify", editable = true }
pytest-pyodide = ">=0.58.3, <0.59"
itkwasm-compare-images = ">=5.2.0, <6"
itkwasm-image-io = ">=1.3.0, <2"
itkwasm-compare-meshes = ">=0.4.0, <0.5"
itkwasm-mesh-io = ">=1.4.1, <2"
itkwasm-mesh-to-poly-data = ">=1.1.0, <2"

[feature.python.tasks.test-wasi]
cmd = "pytest"
cwd = "python/itkwasm-compress-stringify-wasi"
description = "Run tests for itkwasm-compress-stringify-wasi"

[feature.python.tasks.download-pyodide]
cmd = "curl -L https://github.com/pyodide/pyodide/releases/download/0.26.3/pyodide-0.26.3.tar.bz2 -o pyodide.tar.bz2 && tar xjf pyodide.tar.bz2 && rm pyodide.tar.bz2"
outputs = ["pyodide"]
description = "Download Pyodide"

[feature.python.tasks.test-emscripten]
cmd = "mkdir -p dist/pyodide && cp -r ../../pyodide dist/ && hatch build -t wheel ./dist/pyodide/ && pytest --dist-dir=./dist/pyodide --rt=chrome"
cwd = "python/itkwasm-compress-stringify-emscripten"
depends-on = ["download-pyodide"]
description = "Run tests for itkwasm-compress-stringify-emscripten"

[feature.python.tasks.serve-emscripten]
cmd = "mkdir -p dist/pyodide && cp -r ../../pyodide dist/ && hatch build -t wheel ./dist/pyodide/ && echo \"\nVisit http://localhost:8877/console.html\n\" && python -m http.server --directory=./dist/pyodide 8877"
cwd = "python/itkwasm-compress-stringify-emscripten"
depends-on = ["download-pyodide"]
description = "Serve itkwasm-compress-stringify-emscripten for development"

[feature.python.tasks.test-dispatch]
cmd = "mkdir -p dist/pyodide && cp -r ../../pyodide dist/ && hatch build -t wheel ./dist/pyodide/ && pytest --dist-dir=./dist/pyodide --rt=chrome"
cwd = "python/itkwasm-compress-stringify"
depends-on = ["download-pyodide"]
description = "Run tests for itkwasm-compress-stringify"

[feature.python.tasks.serve-dispatch]
cmd = "mkdir -p dist/pyodide && cp -r ../../pyodide dist/ && hatch build -t wheel ./dist/pyodide/ && echo \"\nVisit http://localhost:8877/console.html\n\" && python -m http.server --directory=./dist/pyodide 8877"
cwd = "python/itkwasm-compress-stringify"
depends-on = ["download-pyodide"]
description = "Serve itkwasm-compress-stringify for development"

[feature.python.tasks.test-python]
cmd = "echo 'Testing all Python packages'"
depends-on = ["test-wasi", "test-emscripten", "test-dispatch"]
description = "Run tests for all Python packages"

[environments]
python = ["python"]
