[project]
authors = ["Matt McCormick <matt.mccormick@kitware.com>"]
channels = ["conda-forge"]
description = "ITK-Wasm native build and test configuration."
name = "ITK-Wasm"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = ["itk_wasm_env.bash"]

[tasks]
clean = "git clean -fdx"

[dependencies]

[feature.native.tasks.clone-itk]
cmd = ["stat", "$ITK_WASM_ITK_SOURCE_DIR", ">/dev/null", "||",
  "git", "clone",
    "--branch=$ITK_WASM_ITK_BRANCH",
    "$ITK_WASM_ITK_REPOSITORY",
    "$ITK_WASM_ITK_SOURCE_DIR"]
# Note: pixi does not seem to reliably support activation environmental variables in task inputs / outputs
outputs = ["native/ITK/LICENSE"]

[feature.native.tasks.switch-dcmtk]
cmd = ["sed", "-i", "-e",
  "/^set(DCMTK_GIT_REPOSITORY/c\\set(DCMTK_GIT_REPOSITORY \"$ITK_WASM_DCMTK_REPOSITORY\")",
  "$ITK_WASM_ITK_SOURCE_DIR/Modules/ThirdParty/DCMTK/DCMTKGitTag.cmake",
  "&&",
  "sed", "-i", "-e",
  "/^set(DCMTK_GIT_TAG/c\\set(DCMTK_GIT_TAG \"$ITK_WASM_DCMTK_GIT_TAG\")",
  "$ITK_WASM_ITK_SOURCE_DIR/Modules/ThirdParty/DCMTK/DCMTKGitTag.cmake"]
depends-on = ["clone-itk"]

[feature.native.tasks.configure-itk]
cmd = '''cmake -B$ITK_WASM_ITK_BUILD_DIR -S$ITK_WASM_ITK_SOURCE_DIR -GNinja
  -DCMAKE_CXX_STANDARD:STRING=20
  -DCMAKE_BUILD_TYPE:STRING=Debug
  -DCMAKE_CONFIGURATION_TYPES:STRING=Debug
  -DBUILD_EXAMPLES:BOOL=OFF
  -DBUILD_TESTING:BOOL=OFF
  -DBUILD_SHARED_LIBS:BOOL=OFF
  -DBUILD_STATIC_LIBS:BOOL=ON
  -DDCMTK_LINK_STATIC:BOOL=ON
  -DITK_LEGACY_REMOVE:BOOL=ON
  -DITK_BUILD_DEFAULT_MODULES:BOOL=ON
  -DITKGroup_IO:BOOL=ON
  -DH5_HAVE_GETPWUID:BOOL=OFF
  -DModule_ITKIOMINC:BOOL=ON
  -DModule_MGHIO:BOOL=ON
  -DModule_IOMeshSWC:BOOL=ON
  -DModule_IOScanco:BOOL=ON
  -DModule_IOFDF:BOOL=ON
  -DModule_ITKDCMTK:BOOL=ON
  -DModule_ITKImageFunction:BOOL=ON
  -DModule_MinimalPathExtraction:BOOL=ON
  -DModule_MorphologicalContourInterpolation:BOOL=ON
  -DModule_SmoothingRecursiveYvvGaussianFilter:BOOL=ON
  -DModule_Cuberille:BOOL=ON
  -DModule_TotalVariation:BOOL=ON
  -DModule_IOMeshSTL:BOOL=ON
  -DModule_GenericLabelInterpolator:BOOL=ON
  -DModule_MeshToPolyData=ON
  -DDO_NOT_BUILD_ITK_TEST_DRIVER:BOOL=ON
  -DOPJ_USE_THREAD:BOOL=OFF
  -DDCMTK_WITH_THREADS:BOOL=OFF
  -DDCMTK_BUILD_APPS:BOOL=OFF
  -DNO_FLOAT_EXCEPTIONS:BOOL=ON
  -DITK_MSVC_STATIC_RUNTIME_LIBRARY=ON'''
depends-on = ["switch-dcmtk"]
# Note: pixi does not seem to reliably support activation environmental variables in task inputs / outputs
# outputs = ["$ITK_WASM_ITK_BUILD_DIR/CMakeFiles/"]
outputs = ["native/ITK-build/CMakeFiles/**"]

[feature.native.tasks.build-itk]
cmd = "cmake --build $ITK_WASM_ITK_BUILD_DIR"
depends-on = ["configure-itk"]
outputs = ["native/ITK-build/**"]

[feature.native.tasks.configure-itk-wasm]
cmd = '''cmake -B$ITK_WASM_NATIVE_WORKSPACE/ITK-Wasm-build -S. -GNinja
  -DITK_DIR:PATH=$ITK_WASM_ITK_BUILD_DIR
  -DBUILD_TESTING:BOOL=ON
  -DCMAKE_CXX_STANDARD:STRING=20
  -DCMAKE_BUILD_TYPE:STRING=Debug'''
depends-on = ["build-itk"]
outputs = ["native/ITK-Wasm-build/CMakeFiles/"]

[feature.native.tasks.build-itk-wasm]
cmd = "cmake --build $ITK_WASM_NATIVE_WORKSPACE/ITK-Wasm-build"
depends-on = ["configure-itk-wasm"]

[feature.native.tasks.test-itk-wasm]
cmd = "ctest --test-dir $ITK_WASM_NATIVE_WORKSPACE/ITK-Wasm-build"
depends-on = ["build-itk-wasm"]

[feature.native.dependencies]
cmake = ">=3.30.2,<4"
cxx-compiler = ">=1.7.0,<2"
ninja = ">=1.12.1,<2"

[environments]
native = ["native"]
