packages:
  - 'packages/**'
  - 'examples/debugging'
  - 'examples/node-js'
  - 'examples/inputs-outputs'
  - 'examples/inputs-outputs/typescript'
  - 'examples/different-input-types'
  - 'examples/hello-world'
  - 'examples/mean-squares-versor-registration'
  - 'examples/mean-squares-versor-registration/typescript'
  - '!packages/core/typescript/create-itk-wasm/test/**'
  - '!**/src'
  - '!**/dist'
  - '!**/pyodide'
