[project]
authors = ["Matt McCormick <matt@mmmccormick.com>"]
channels = ["conda-forge"]
description = "Compare images with a tolerance for regression testing."
name = "compare-images"
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pnpm = ">=9.12.1,<10"

[feature.python.dependencies]
pytest = ">=8.3.3,<9"
pip = ">=24.2,<25"

[feature.python.pypi-dependencies]
hatch = ">=1.13.0, <2"
itkwasm-compare-images-wasi = { path = "python/itkwasm-compare-images-wasi", editable = true }
itkwasm-compare-images = { path = "python/itkwasm-compare-images", editable = true }
pyodide-py = ">=0.26.3, <0.27"
pytest-pyodide = ">=0.58.3, <0.59"
itk-webassemblyinterface = ">=1.0b175, <2"
itkwasm-image-io = ">=1.3.0, <2"

[feature.python.tasks.test-wasi]
cmd = "pytest"
cwd = "python/itkwasm-compare-images-wasi"
description = "Run tests for itkwasm-compare-images-wasi"

[feature.python.tasks.download-pyodide]
cmd = '''curl -L https://github.com/pyodide/pyodide/releases/download/0.26.3/pyodide-0.26.3.tar.bz2 -o pyodide.tar.bz2 &&
  tar xjf pyodide.tar.bz2 &&
  rm pyodide.tar.bz2'''
outputs = ["pyodide"]
description = "Download Pyodide"

[feature.python.tasks.test-emscripten]
cmd = '''mkdir -p dist/pyodide &&
  cp -r ../../pyodide dist/ &&
  hatch build -t wheel ./dist/pyodide/ &&
  pytest --dist-dir=./dist/pyodide --rt=chrome'''
cwd = "python/itkwasm-compare-images-emscripten"
depends-on = ["download-pyodide"]
description = "Run tests for itkwasm-compare-images-emscripten"

[feature.python.tasks.serve-emscripten]
cmd = '''mkdir -p dist/pyodide &&
  cp -r ../../pyodide dist/ &&
  hatch build -t wheel ./dist/pyodide/ &&
  echo \"\nVisit http://localhost:8877/console.html\n\" &&
  python -m http.server --directory=./dist/pyodide 8877'''
cwd = "python/itkwasm-compare-images-emscripten"
depends-on = ["download-pyodide"]
description = "Serve itkwasm-compare-images-emscripten for development"

[feature.python.tasks.test-dispatch]
cmd = '''mkdir -p dist/pyodide &&
  cp -r ../../pyodide dist/ &&
  hatch build -t wheel ./dist/pyodide/ &&
  cp ../itkwasm-compare-images-emscripten/dist/pyodide/itkwasm_compare_images_emscripten*.whl ./dist/pyodide/ &&
  pytest --dist-dir=./dist/pyodide --rt=chrome'''
cwd = "python/itkwasm-compare-images"
depends-on = ["download-pyodide"]
description = "Run tests for itkwasm-compare-images"

[feature.python.tasks.serve-dispatch]
cmd = '''mkdir -p dist/pyodide &&
  cp -r ../../pyodide dist/ &&
  hatch build -t wheel ./dist/pyodide/ &&
  echo \"\nVisit http://localhost:8877/console.html\n\" &&
  python -m http.server --directory=./dist/pyodide 8877'''
cwd = "python/itkwasm-compare-images"
depends-on = ["download-pyodide"]
description = "Serve itkwasm-compare-images for development"

[feature.python.tasks.test-python]
cmd = "echo 'Testing all Python packages'"
depends-on = ["test-wasi", "test-emscripten", "test-dispatch"]
description = "Run tests for all Python packages"

[environments]
python = ["python"]
