version: 2
jobs:
  build-test-node-example:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Test Node.js example
          no_output_timeout: 0.5h
          command: |
            cd examples/Node.js
            npm install
            npm run test

  build-test-webpack-example:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Test Webpack example
          no_output_timeout: 0.5h
          command: |
            . ./.circleci/load-nvm.sh
            nvm install v10.15.3
            nvm alias default v10.15.3
            cd examples/Webpack
            npm install
            npm run build
            npm run test

  build-test-unpkgio-example:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Test Unpkg IO example
          no_output_timeout: 0.5h
          command: |
            . ./.circleci/load-nvm.sh
            nvm install v10.15.3
            nvm alias default v10.15.3
            cd examples/UnpkgIO
            npm install
            npm run build
            npm run test

  build-test-nodejs-hello-world-example:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Test Node.js Hello World examlpe
          no_output_timeout: 0.5h
          command: |
            . ./.circleci/load-nvm.sh
            nvm install v10.15.3
            nvm alias default v10.15.3
            cd examples/NodeHelloWorld
            npm install
            npm run build
            npm run test

workflows:
    version: 2

    build-test-examples:
      jobs:
        - build-test-node-example:
            filters:
              branches:
                ignore:
                  - gh-pages
        - build-test-webpack-example:
            filters:
              branches:
                ignore:
                  - gh-pages
        - build-test-unpkgio-example:
            filters:
              branches:
                ignore:
                  - gh-pages
        - build-test-nodejs-hello-world-example:
            filters:
              branches:
                ignore:
                  - gh-pages
