name: C++,Native Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ITKMeshToPolyData-git-tag: "v0.11.0"

jobs:
  cxx-build-workflow:
    # itk-wasm branch
    uses: thewtex/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@6868c9879405def5d7532e0437b57e78cbe0b6ea
    with:
      itk-module-deps: 'MeshToPolyData@v0.11.0'
      ctest-options: '-E itkPipelineTest'

  python-build-workflow:
    # itk-wasm branch
    uses: thewtex/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@6868c9879405def5d7532e0437b57e78cbe0b6ea
    with:
      itk-module-deps: 'InsightSoftwareConsortium/ITKMeshToPolyData@v0.11.0'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
