name: C++,Native Python

on: [push,pull_request]

env:
  itk-git-tag: "v5.3.0"
  itk-wheel-tag: "v5.3.0"
  ITKMeshToPolyData-git-tag: "v0.10.0"

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@03626a23c22246e89e36c7e918a158c440f9b099
    with:
      itk-module-deps: 'MeshToPolyData@v0.10.0'
      ctest-options: '-E itkPipelineTest'

  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@03626a23c22246e89e36c7e918a158c440f9b099
    with:
      itk-module-deps: 'InsightSoftwareConsortium/ITKMeshToPolyData@v0.10.0'
      itk-python-package-org: 'tbirdso'
      itk-python-package-tag: 'c81fd6891ff25a05df5d61459366ab6c5c6f9a65'
      manylinux-platforms: '[]'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
