name: C++,Native Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ITKMeshToPolyData-git-tag: "v0.11.0"

jobs:
  cxx-build-workflow:
    uses: thewtex/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@0b6e8918614196db3b8dde499cf16f2398c78474
    with:
      itk-module-deps: 'MeshToPolyData@v0.11.0'
      ctest-options: '-E itkPipelineTest'

  python-build-workflow:
    uses: thewtex/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@0b6e8918614196db3b8dde499cf16f2398c78474
    with:
      itk-module-deps: 'InsightSoftwareConsortium/ITKMeshToPolyData@v0.11.0'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
