name: C++,Native Python

on: [push,pull_request]

env:
  itk-git-tag: "v5.4rc01"
  itk-wheel-tag: "v5.3.0"
  ITKMeshToPolyData-git-tag: "v0.11rc01"

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@03626a23c22246e89e36c7e918a158c440f9b099
    with:
      itk-module-deps: 'MeshToPolyData@v0.11rc01'
      ctest-options: '-E itkPipelineTest'

  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@03626a23c22246e89e36c7e918a158c440f9b099
    with:
      itk-module-deps: 'InsightSoftwareConsortium/ITKMeshToPolyData@v0.11rc01'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
