name: C++,Native Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ITKMeshToPolyData-git-tag: "v0.11.0"

jobs:
  cxx-build-workflow:
    # itk-wasm branch
    uses: thewtex/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@6868c9879405def5d7532e0437b57e78cbe0b6ea
    with:
      itk-module-deps: 'MeshToPolyData@v0.11.0'
      ctest-options: '-E itkPipelineTest'
      # release-5.4 2025-07-02
      itk-git-tag: '276a52a5c0b1a5df67c9a2b0fdcd0bc75504e011'

  #python-build-workflow:
    ## itk-wasm branch
    #uses: thewtex/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@6868c9879405def5d7532e0437b57e78cbe0b6ea
    #with:
      #itk-module-deps: 'InsightSoftwareConsortium/ITKMeshToPolyData@v0.11.0'
      #manylinux-platforms: '["_2_28-x64","_2_28-aarch64"]'
    #secrets:
      #pypi_password: ${{ secrets.pypi_password }}
