name: Examples

on: [push,pull_request]

jobs:
  test-node-example:
    name: Node.js
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./examples/Node.js

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install
      run: |
        npm install

    - name: Test
      run: |
        npm run test

  build-hello-world-example:
    name: Hello World Build
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./examples/HelloWorld

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Save wasm builds
      uses: actions/upload-artifact@v2
      with:
        name: hello-world-build
        if-no-files-found: error
        path: |
          examples/HelloWorld/web-build
          examples/HelloWorld/wasi-build


  test-hello-world-example:
    name: Hello World Test
    needs: build-hello-world-example
    runs-on: ubuntu-20.04
    container: cypress/browsers:node16.13.2-chrome97-ff96

    defaults:
      run:
        working-directory: ./examples/HelloWorld

    steps:
    - uses: actions/checkout@v2

    - name: Load wasm builds
      uses: actions/download-artifact@v2
      with:
        name: hello-world-build
        path: examples/HelloWorld

    - name: Test
      uses: cypress-io/github-action@v2
      with:
        working-directory: ./examples/HelloWorld
        browser: chrome
        start: npm start

  test-umd-example:
    name: UMD
    runs-on: ubuntu-20.04
    container: cypress/browsers:node16.13.2-chrome97-ff96

    steps:
    - uses: actions/checkout@v2

    - name: Test
      uses: cypress-io/github-action@v2
      with:
        working-directory: ./examples/UMD
        browser: chrome
        start: npm start

  test-webpack-example:
    name: Webpack
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./examples/Webpack

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Test
      run: |
        ./test/run.sh

  test-debugging-example:
    name: Debugging
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./examples/Debugging

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run native-build
        npm run emscripten-build-release
        npm run emscripten-build-debug
        npm run wasi-build-debug
