name: Examples

on: [push]

jobs:
  test-node-example:
    name: Node.js
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./examples/Node.js

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install 
      run: |
        npm install

    - name: Test
      run: |
        npm run test

  build-test-node-example:
    name: Node Hello World
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./examples/NodeHelloWorld

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install 
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Test
      run: |
        npm run test