name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-esm-example:
    defaults:
      run:
        working-directory: ./examples/esm
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  test-vite-example:
    defaults:
      run:
        working-directory: ./examples/vite
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  test-webpack-example:
    defaults:
      run:
        working-directory: ./examples/webpack
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  test-itk-wasm:
    name: itk-wasm browser tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
          tool-cache: true

      - name: Pull latest Docker images
        run: |
          ./src/docker/pull.sh --no-debug

      - name: Install
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Install dependencies for itk-wasm
        run: pnpm install
        working-directory: packages/core/typescript/itk-wasm

      - name: Build itk-wasm
        run: |
          pnpm run --aggregate-output --filter itk-wasm build

      - name: Build @itk-wasm/demo-app
        run: |
          pnpm run --aggregate-output --filter '@itk-wasm/demo-app' build

      - name: Build build:gen:typescript
        run: |
          pnpm run --aggregate-output build:gen:typescript

      - name: Build itk-wasm
        run: |
          pnpm run --aggregate-output --filter itk-wasm build
          # Test deps
          pnpm run --aggregate-output --filter "@itk-wasm/demo-app" build
          pnpm run --aggregate-output --filter "@itk-wasm/mesh-io" build
          pnpm run --aggregate-output --filter "@itk-wasm/transform-io" build
          pnpm run --aggregate-output --filter "@itk-wasm/image-io" build

      - name: Run Playwright tests
        working-directory: ./packages/core/typescript/itk-wasm
        run: pnpm run test:browser

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/core/typescript/itk-wasm/playwright-report/
          retention-days: 30