name: Python Wasm

on: [push,pull_request]

jobs:
  test-itkwasm:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./packages/core/python/itkwasm
        run: |
          python -m pip install --upgrade pip
          cd test/test-accelerator
          python -m pip install -e "."
          cd -
          python -m pip install -e ".[test]"
      - name: Test with pytest
        working-directory: ./packages/core/python/itkwasm
        run: |
          pytest --junitxml=junit/test-results.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'packages/core/python/itkwasm/junit/test-results*.xml'

  test-pythonpackages:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch pytest
      - name: Test compress-stringify wasi
        working-directory: ./packages/compress-stringify/python/itkwasm-compress-stringify-wasi
        run: |
          python -m pip install -e .
          pytest
          hatch run test
      - name: Test compress-stringify
        working-directory: ./packages/compress-stringify/python/itkwasm-compress-stringify
        run: |
          python -m pip install -e .
          pytest