name: WASI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -leo pipefail {0} {0}

env:
  OCI_EXE: docker

jobs:
  build-test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main

    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install
      uses: pnpm/action-setup@v4
      with:
        run_install: true

    - name: Build
      run: |
        pnpm run --sequential --aggregate-output build:wasi:debug

    - name: Test
      run: |
        pnpm run --sequential --aggregate-output test:wasi
