name: WASI

on: [push,pull_request]

defaults:
  run:
    shell: bash -leo pipefail {0} {0}

env:
  OCI_EXE: docker

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main

    - name: Pull latest Docker images
      run: |
        ./src/docker/pull.sh --no-debug

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install
      uses: pnpm/action-setup@v4
      with:
        run_install: true

    - name: Build
      run: |
        pnpm run --aggregate-output build:wasi:debug

    - name: Test
      run: |
        pnpm run --aggregate-output test:wasi
